version: "3.7"

services:
  simple_chat:
    build: .
    ports:
      - 8080:8080
    links:
      - redis
    environment:
      REDIS_ADDRESS: redis:6379
    depends_on:
      - redis
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data:rw
  redis-tst:
    image: redis:5-alpine
    ports:
      - 6378:6378

volumes:
  redis_data:
    driver: local
